export const paths = {
  home: "/",
  auth: {
    signIn: "/auth/sign-in",
  },
  dashboard: {
    overview: "/dashboard",
    manageCenter: "/dashboard/manage-center",
    users: "/dashboard/users",
    manageVehicle: "/dashboard/manage-vehicle",
    manageDailyKm: "/dashboard/manage-daily-km",
    manageFuel: "/dashboard/manage-fuel",
    manageRoles: "/dashboard/manage-roles",
    manageRoute:"/dashboard/manage-route",
    fuelStation:"/dashboard/fuel-station",
    addCenter: "/dashboard/add-center",
    editCenter: "/dashboard/update-center/:id",
    adduser: "/dashboard/add-user",
    edituser: "/dashboard/edit-user",
    addVehicle: "/dashboard/add-vehicleManage",
    editVehicle:"/dashboard/update-vehicleManage",
    addDailyKm:"add-dailyKm",
    updateDailyKm:"update-dailyKm/:id",
    addfuel:"/dashboard/add-fuel",
    fuelReceipt:"/dashboard/fuel-receipt",
    manageFuelReceipt:"/dashboard/fuel-receipt/manage",
    manageVehicleFuel:"/dashboard/fuel-receipt/list",
    manageDailyKmList:'/dashboard/manage-dailyKm-list',
    editfuel:"/dashboard/edit-fuel/:id",
    addRole: "/dashboard/add-role",
    updateRole: "/dashboard/update-role/:id",
    addRoute:"/dashboard/add-route",
    updateRoute:"/dashboard/update-route/:id",
    addfuelstation:"/dashboard/add-fuelStation",
    updatefuelstation:"/dashboard/update-fuelStation/:id",
  },
  reports: {
    sitewiseReport: "/dashboard/sitewise-report",
    fuelActivityReport: "/dashboard/fuelActivity-report",
    dieselCenterWiseReport: "/dashboard/diesel-centerwise-report",
    dieselPumpWiseReport: "/dashboard/leakage-report",
  },
} as const;
